### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by rtonata88** [yigitm/todo-list#6]
Great work done so far. However, please correct the following:

Remove the following lines
`/* eslint-disable no-restricted-globals */`
`/* eslint-disable import/no-cycle */`

This is because you have modules calling / referencing each other, therefore going in circles. 

The following features are not working:

- Adding of a task
- Delete task
- Edit task
- Please fix linter errors
- Also fix an error in `backend.js`

**Comment by yigitm** [comment]
Thank you so much. Issues are fixed.
